package fi.kela.drools.general;

public enum AsianTila {
	EHDOTETTU, 
	SAAPUNUT, 
	KASITTELYSSA, 
	LASKETTU,
	PAATOSLUONNOS_MUODOSTETTU, 
	ODOTTAA_VARMENNUSTA, 
	PERUTTU, 
	RATKAISTU, 
	SULJETTU, 
	POISTETTU,
	POIMITTU_HAVITETTAVAKSI, 
	HÄVITETTY 
}
